export const UI = {

    theme: {
        dark: '🌙 暗色',
        light: '☀️ 亮色',
        lofi: '📼 低保真',
    },

    iconPack: {
        sectionLabel: '📦 图标包管理',
        uploadButton: '📤 上传图标包',
        packNamePlaceholder: '图标包名称',
        fileInputLabel: '选择 zip 文件',
        themeLabel: '绑定主题',
        selectAll: '全选',
        hint: '命名规则：键名.png/.svg（如 site.png、box-lid.svg）；支持子目录组织，文件名（去扩展名）即图标键；推荐尺寸 64–512px；仅支持 PNG / SVG。',
        deleteButton: '🗑️ 删除',
        emptyList: '暂无图标包',
        validationErrorsTitle: '安全性检查未通过',
        validationWarningsTitle: '检查提示（可继续上传）',
        confirmUpload: '仍要上传',
        cancelUpload: '取消上传',
        missingKeys: '缺少图标键',
        unknownKeys: '未识别图标',
        outOfRange: '尺寸超出推荐范围',
        docTitle: '🎨 图标键名参考',
        docTabDark: '🌙 暗色',
        docTabLight: '☀️ 亮色',
        docTabLofi: '📼 低保真',
        docLegendDefault: '● 灰色 = 使用默认图标',
        docLegendCustom: '<span style="color: #4CAF50;">●</span> 绿色 = 已有自定义图标',
        docGroupBase: '基础 UI 图标',
        docGroupBox: '超现实箱子图标',
        uploadSuccess: '图标包已上传',
        uploadFailed: '图标包上传失败',
        deleteSuccess: '图标包已删除',
        themeRequired: '至少选择一个主题',
        nameRequired: '请输入图标包名称',
    },

    gradient: {
        directionBottom: '上→下',
        directionTop: '下→上',
        directionLeft: '右→左',
        directionRight: '左→右',
        directionBottomRight: '左上→右下',
        directionBottomLeft: '右上→左下',
    },

    common: {
        siteTitle: 'REVACHOL',
        siteSubtitle: '· 原创角色档案馆 ·',
        appName: 'REVACHOL',
        loading: '加载中...',
        close: '关闭',
        cancel: '取消',
        save: '保存',
        confirm: '确认',
        delete: '删除',
        edit: '编辑',
        back: '返回',
        more: '更多',
        searchPlaceholder: '🔍 找点什么？',
        noResults: '无',
        unknown: '未知',
        searchResultCount: (count) => `找到 ${count} 个结果`,
        searchResultItem: (index, total, title) => `结果 ${index}/${total}: ${title}`,
        toggleVisible: '切换可见性',
    },

    login: {
        triggerLabel: '登录',
        welcomeText: '欢迎访客',
        adminLabel: '管理员',
        adminWelcome: '欢迎管理员',
        modalTitle: '🔐 管理员登录',
        usernameLabel: '用户名',
        passwordLabel: '密码',
        loginButton: '登录',
        hint: '普通用户无需登录',
        placeholderUsername: '请输入用户名',
        placeholderPassword: '请输入密码',
        errorEmpty: '用户名和密码不能为空',
        errorInvalid: '用户名或密码错误',
    },

    admin: {
        panelTitle: '⚙️ 管理',
        collapseIcon: '▶',
        expandIcon: '▼',
        avatarUploadLabel: '📷 上传头像',
        avatarHint: '点击上传，可裁剪为正方形',
        textureUploadLabel: '🖼️ 纹理贴图',
        textureApplyButton: '应用纹理',
        textureRemoveButton: '移除纹理',
        textureOpacityLabel: '🎨 纹理透明度',
        watermarkTextLabel: '📝 水印文字',
        watermarkOpacityLabel: '🎨 水印透明度',
        watermarkApplyButton: '应用水印设置',
        videoOpacityLabel: '🎥 视频最大透明度',
        videoOpacityHint: '控制视频在页面顶部的最亮程度（0=完全透明，1=最亮）',
        bgModeLabel: '🎨 背景模式',
        bgModeSolid: '纯色',
        bgModeGradient: '渐变',
        gradientColorLabel: '🌈 颜色选择',
        gradientColorHint: '选择2~3种颜色，渐变将从上到下过渡',
        gradientDirectionLabel: '↕ 方向',
        gradientFeatherLabel: '🪶 羽化值',
        gradientFeatherHint: '数值越大，颜色过渡越柔和',
        gradientApplyButton: '✅ 应用渐变',
        paletteSaveButton: '💾 存入色卡',
        paletteNamePlaceholder: '色卡名称（可选）',
        paletteListLabel: '📚 色卡库',
        paletteEmpty: '暂无色卡',
        paletteApply: '应用色卡',
        paletteDelete: '删除色卡',
        decoLibraryLabel: '🖼️ 贴图库管理',
        decoUploadButton: '📤 上传贴图',
        decoUploadHint: '支持 PNG, WebP, JPG 格式（自动压缩为 WebP）',
        decoLoading: '加载中...',
        decoEmpty: '📭 暂无贴图',
        decoEmptyHint: '点击上方 "📤 上传贴图" 添加',
        decoItemPlaced: '📍已放置',
        decoItemUnplaced: '📦未放置',
        decoStyleLabel: '切换样式',
        decoStyleFixed: '悬浮',
        decoStyleAbsolute: '贴纸',
        decoDuplicate: '复制贴图',
        decoRename: '重命名',
        decoEditPos: '编辑位置',
        decoDownload: '下载贴图',
        decoDelete: '从库中删除',
        customTextureSectionLabel: '🎨 自定义贴图',
        siteIconLabel: '🌐 站点图标',
        siteIconUploadButton: '📤 上传站点图标',
        siteIconHint: '建议 130×130px 展示；SVG / PNG 透明背景',
        directoryCollapsedIconLabel: '📂 目录收起图标',
        directoryExpandedIconLabel: '📁 目录展开图标',
        directoryHeaderIconLabel: '📜 目录本身图标',
        directoryCollapsedIconHint: '默认 📂；建议 48×48px（2x），显示为 24×24px',
        directoryExpandedIconHint: '默认 📁；建议 48×48px（2x），显示为 24×24px',
        directoryHeaderIconHint: '默认 📜；建议 24×24px 透明图标',
        toolbarCollapsedIconLabel: '🧰 顶部工具栏 — 收起图标',
        toolbarExpandedIconLabel: '🧰 顶部工具栏 — 展开图标',
        adminPanelIconLabel: '⚙️ 控制台折叠箭头',
        iconUploadButton: '📤 上传图标',
        iconRestoreDefaultButton: '✖ 恢复默认',
        toolbarCollapsedIconHint: '默认 ⚙；建议 44×44px 透明图标',
        toolbarExpandedIconHint: '默认 ◀；建议 44×44px 透明图标',
        adminPanelIconHint: '默认 ▶/▼；建议 16×16px 透明图标',
        iconSectionToggleTitle: '展开/收缩',
        siteIconPreviewAlt: '站点图标预览',
        iconPreviewAlt: '图标预览',
        restoreDefaultButton: '🗑️ 恢复默认',
        boxLidLabel: '🧰 箱子外观 — 箱盖',
        boxLidUploadButton: '📤 上传箱盖',
        boxLidHint: '建议上传 120×22px 左右的图片。支持 PNG / JPEG / WebP',
        boxBodyLabel: '🧰 箱子外观 — 箱体',
        boxBodyUploadButton: '📤 上传箱体',
        boxBodyHint: '建议上传 120×78px 左右的图片。支持 PNG / JPEG / WebP',
        boxItemLabel: '🎁 物品贴图',
        boxItemSelectPlaceholder: '— 选择物品 —',
        boxItemOptions: {
            feather: '🪶 一根白色羽毛',
            coin: '🪙 一枚旧硬币',
            key: '🗝️ 一把生锈的钥匙',
            note: '📄 一张字条',
            sand: '⏳ 一粒沙',
            thread: '🧵 一颗纽扣',
            mirror: '🪞 一面小镜子',
            void: '🌫️ （什么都没有）',
        },
        boxItemUploadButton: '📤 上传贴图',
        boxItemRestoreEmojiButton: '🗑️ 恢复 Emoji',
        boxItemHint: '选择物品后上传自定义贴图，开箱时将显示贴图而非 Emoji',
        themeSectionLabel: '🎨 主题切换',
        themeHint: '点击切换主题，偏好自动保存',
        confirmPosButton: '✅ 确认位置',
        cancelPosButton: '❌ 取消编辑',
        articleEditorLabel: '📝 文章管理',
        articleEditorButton: '📝 进入文章编辑器',
        articleEditorHint: '在编辑器中管理文章和分类',
        articleVisibilityLabel: '📄 文章可见性控制',
        articleVisibilityHint: '请使用左侧 <strong>📜 目录树</strong> 中每篇文章旁的 <span style="color: var(--color-success);">👁️</span> / <span style="color: var(--color-border);">🚫</span> 按钮进行可见性切换。',
        articleVisibilityHintAdmin: '管理员登录后，在目录树中每个文章节点右侧会出现可见性控制按钮。',
        logoutButton: '退出登录',
        articleEmpty: '暂无文章，点击 “新建文章” 创建',
        positionModeEnter: '📌 进入位置管理',
        positionModeSave: '💾 保存更改',
        positionModeCancel: '❌ 取消',
        positionModeHint: '拖拽文章或文件夹调整位置，保存后生效',
    },

    directory: {
        emptyTree: '空无一人',
        emptyFolder: '空文件夹',
        loading: '加载中...',
        folderIconCollapsed: '📂',
        folderIconExpanded: '📁',
        articleIcon: '📄',
        toggleVisible: '展开',
        toggleHidden: '折叠',
        menuEditArticle: '✏️ 编辑内容',
        menuRenameArticle: '🔄 重命名',
        menuNewArticle: '📄 新建文章',
        menuNewFolder: '📁 新建子文件夹',
        menuNewRootFolder: '📁 新建根文件夹',
        menuDeleteArticle: '❌ 删除文章',
        menuRenameFolder: '📝 重命名文件夹',
        menuDeleteFolderOnly: '🗑️ 删除文件夹（仅文件夹）',
        menuDeleteFolderWithArticles: '🗑️ 删除文件夹及文章',
        menuNewArticleRoot: '📄 新建文章',
        menuNewFolderRoot: '📁 新建根文件夹',
        folderNoArticles: (name) => `📁 "${name}" 文件夹暂无文章`,
        dragDropHint: '📥 拖拽到此空白区域 → 移动到平级位置',
    },

    articles: {
        empty: '⚡ 意识流空转 ⚡<br><small>尚未记录任何角色</small>',
        cardHint: '点击查看详情',
        cardMetaPrefix: '✍️ 最后修改 · ',
        loadMore: '📖 加载更多角色...',
        endMessage: '✨ 已经到底了 ✨',
        bottomToastEnd: '✨ 已经到底了 ✨',
        defaultCategory: '未分类档案',
        defaultTitle: '无名者',
        defaultContent: '无描述',
        unknownTime: '未知纪元',
        loading: '⏳ 正在加载角色...',
    },

    detail: {
        tabClose: '✕',
        paneMinimize: '➖',
        paneFullscreen: '⛶',
        paneFullscreenExit: '⤢',
        paneClose: '✕',
        minimizeTitle: '最小化到左下角',
        minimizeToast: '已最小化到页面顶部',
        restoreFromMinimize: '↩',
        fullscreenTitle: '全屏/窗口切换',
        closeAllConfirm: '关闭所有标签页？',
        invisibleToast: '该文章已被设为不可见（管理员可继续阅读）',
        invisibleConfirm: '该文章已被管理员设置为不可见，点击确定关闭当前阅读窗口。',
        defaultTitle: '无标题',
        defaultContent: '无内容',
    },

    deco: {
        menuDuplicate: '📋 复制',
        menuPaste: '📋 粘贴',
        menuRename: '✏️ 重命名',
        menuEdit: '📐 移动和缩放',
        menuToggleStyle: '🔄 切换样式',
        menuRemovePage: '❌ 从网页删除',
        menuDeleteLib: '🗑️ 从库中删除',
        toggleStyleLabel: (style) => `🔄 切换样式`,
        pasteDisabled: '剪贴板为空',
        renamePrompt: '输入新名称：',
        deleteConfirm: (name) => `确定要从贴图库中删除 "${name}" 吗？`,
        duplicateSuccess: (name) => `已复制贴图 "${name}"`,
        deleteSuccess: (name) => `已删除 "${name}"`,
        editPosToast: '拖动贴图调整位置，点击"确认位置"保存',
        styleSwitched: '已切换',
        alreadyStyle: (style) => `已经是 ${style} 样式`,
        noEditing: '没有正在编辑的贴图',
        positionConfirmed: '位置已确认',
        editCancelled: '已取消编辑',
        useLibraryEdit: '请使用贴图库的"编辑位置"功能',
        formatNotSupported: '格式不正确，只支持 PNG、WebP、JPG 格式',
        removedFromPage: '已从页面移除',
        pasteSuccess: '粘贴成功',
    },

    decoEdit: {
        toolbarTitle: '📐 拖拽贴纸移动 · 拖拽右下角 ◢ 调整大小',
        confirmBtn: '✅ 确认更改',
        resetBtn: '🔄 重置',
        cancelBtn: '❌ 取消',
        confirmToast: '✅ 贴纸位置和大小已保存',
        resetToast: '🔄 已重置到进入时的状态',
        cancelToast: '已取消更改',
        menuLabel: '📐 移动和缩放',
    },

    notification: {
        visibilityChanged: (visible) => `文章已${visible ? '可见' : '不可见'}`,
        visibilityChangedLocal: (visible) => `文章已${visible ? '可见' : '不可见'}（本地模拟）`,
        visibilityAdminOnly: '需要管理员权限',
        visibilityMadeInvisible: '该文章已被管理员设置为不可见，点击确定关闭当前阅读窗口。',
        loginSuccess: '欢迎管理员登录',
        loginFailed: '用户名或密码错误',
        logoutSuccess: '已退出管理员模式',
        decoUploadSuccess: (name) => `贴图 "${name}" 上传成功`,
        decoDuplicateSuccess: (name) => `已复制贴图 "${name}"`,
        decoDeleteConfirm: '确定要从贴图库中删除该贴图吗？',
        decoDeleteSuccess: '已删除',
        decoStyleSwitched: (style) => `已切换为${style}样式`,
        minimized: '已最小化到左下角',
        paletteSaved: '色卡已保存',
        paletteDeleted: '色卡已删除',
        paletteApplied: (name) => `已应用色卡：${name}`,
        paletteDeleteConfirm: '确定删除该色卡吗？',
        bgColorApplied: '背景颜色已应用',
        bgColorReset: '背景颜色已重置',
        gradientApplied: '渐变背景已应用',
        solidApplied: '纯色背景已应用',
        textureApplied: (size) => `纹理已应用（WebP格式，${size}KB）`,
        textureRemoved: '纹理已移除',
        textureUploadFirst: '请先上传纹理图片',
        watermarkApplied: '水印设置已应用',
        moduleNotLoaded: '模块未加载',
        operationFailed: '操作失败，请稍后重试',
        operationSuccess: '操作成功',
        articleSaved: '文章已保存',
        articleDeleted: '文章已删除',
        articleCreated: (title) => `文章 "${title}" 已创建`,
        articleRenameSuccess: '已重命名',
        articleRenameFailed: '重命名失败',
        articleDeleteFailed: '删除失败',
        articleSaveFailed: '保存失败',
        loginRequired: '请登录管理员账号',
        articleDeleteConfirm: '确定要删除这篇文章吗？此操作不可撤销！',
        refreshSuccess: '列表已刷新',
        draftSaved: '草稿已保存',
        draftSaveFailed: '草稿保存失败',
        draftDeleted: '草稿已删除',
        draftRestored: '已恢复草稿版本',
    },

    editor: {
        pageTitle: '文章编辑器 - REVACHOL',
        toolbarTitle: '✎ 文章编辑器',
        saveDraft: '保存草稿',
        publish: '发布',
        cancel: '取消',
        close: '关闭',
        sidebarTitle: '📂 目录',
        sidebarCollapse: '◀',
        sidebarExpand: '☰',
        collapseSidebar: '收起目录',
        expandSidebar: '展开目录',
        historyLabel: '历史',
        hideHistory: '隐藏历史',
        emptyState: '📝<p>点击左侧目录中的文章开始编辑</p><p style="font-size:12px;color:var(--color-text-muted);margin-top:10px;">支持修改标题和正文内容</p>',
        titleLabel: '📌 文章标题',
        contentLabel: '📄 正文内容',
        titlePlaceholder: '输入标题...',
        contentPlaceholder: '在此输入文章内容...',
        saveSuccess: '草稿已保存',
        publishSuccess: '发布成功',
        saveFailed: '草稿保存失败: ',
        publishFailed: '发布失败: ',
        titleRequired: '标题不能为空',
        noArticleSelected: '请先选择一篇文章',
        articleNotFound: '文章不存在',
        shortcutSave: 'Ctrl+S 保存草稿',
        shortcutCancel: 'Esc 取消编辑',
        unsavedConfirm: '有未保存的更改，确定要退出吗？',
        categoryLabel: '📁 分类',
        // 反馈弹窗
        modalDraftSavedTitle: '✅ 草稿已保存',
        modalDraftSavedTime: '保存时间',
        modalPublishSuccessTitle: '🚀 文章已发布',
        modalPublishSuccessDetail: '标题',
        modalConfirmBtn: '确定',
        // 渲染模式切换
        toggleRender: '🔀 切换渲染',
        renderHtml: 'HTML 渲染',
        renderText: '纯文本',
        renderHtmlToast: '已切换为 HTML 渲染模式',
        renderTextToast: '已切换为纯文本模式',
    },

    draft: {
        previewTitle: '📄 草稿预览',
        previewClose: '关闭',
        emptyContent: '（空内容）',
        selectArticle: '请选择文章',
        noHistory: '暂无草稿历史',
        loadFailed: '加载失败',
        saveSuccess: '草稿已保存',
        saveFailed: (msg) => `草稿保存失败: ${msg}`,
        restoreConfirm: (time) => `确定要将文章恢复为 ${time} 的草稿版本吗？`,
        restoreSuccess: '已恢复草稿版本',
        restoreFailed: (msg) => `恢复失败: ${msg}`,
        deleteConfirm: (time) => `确定要删除 ${time} 的草稿吗？`,
        deleteSuccess: '草稿已删除',
        deleteFailed: (msg) => `删除失败: ${msg}`,
        deleteError: '草稿数据异常，无法删除',
        previewBtn: '👁️ 查看',
        restoreBtn: '↩️ 恢复',
        deleteBtn: '🗑️ 删除',
    },

    hero: {
        title: '网站使用说明',
        description: `
            <p><strong>目录说明：</strong>点击左侧 📜 图标展开目录，双击文件夹展开/收起，单击文章跳转。</p>
            <p><strong>文件夹跳转：</strong>单击文件夹跳转到该文件夹第一篇文章。</p>
            <p><strong>文章跳转：</strong>单击文章跳转到对应卡片，双击卡片查看详情。</p>
            <p><strong>访客支持：</strong>浏览所有公开文章，使用搜索框搜索角色，无需登录即可阅读。</p>
        `
    },

    crop: {
        title: '✂️ 裁剪头像',
        previewLabel: '预览',
        cancel: '✗ 取消',
        confirm: '✓ 确认',
    },

    copyright: '© {siteTitle} · {siteSubtitle} · 内容受版权保护 · 未经授权不得截图、复制或传播',

    config: {
        adminUsername: 'admin',
        adminPassword: 'admin123',
        defaultWatermarkText: 'REVACHOL',
        defaultBgColor: '#1a1612', // → var(--color-bg-primary)
        defaultTextureOpacity: 0.12,
        defaultWatermarkOpacity: 0.15,
    },

    toast: {
        positionModeEnter: '已进入位置管理模式，拖拽节点调整位置',
        positionModeExit: '已退出位置管理模式',
        positionModeSaved: '位置更改已保存',
        positionModeCancelled: '已取消，未保存更改',
        positionModeSavePartialError: '部分位置变更保存失败，请检查网络后重试',
        positionModeSaveError: (message) => `保存位置变更失败: ${message}`,

        folderMoveSuccess: (target) => `文件夹已移动到 ${target}`,
        folderMoveFailed: '移动失败',
        folderCreateSuccess: (name) => `文件夹 "${name}" 已创建`,
        folderCreateFailed: '创建失败，可能同名',
        folderDeleteSuccess: '文件夹已删除，子文件夹提升至根目录，文章移至"未分类"',
        folderDeleteFailed: '删除文件夹失败',
        folderNotFound: '文件夹不存在',
        folderDuplicateName: '同级已存在同名文件夹',

        articleMoveSuccess: (category) => `文章已移动到 "${category}"`,
        articleMovePending: '文章已移动（保存后将持久化）',
        articleMoveFailed: (status) => `移动失败: ${status}`,
        articleNotFound: '源文章不存在',
        articleAlreadyInTarget: '文章已在目标文件夹中',
        articleTitleEmpty: '标题不能为空',

        dragTargetFolderNotFound: '目标文件夹不存在',
        dragCannotMoveToSelf: '不能移动到自身',
        dragCannotMoveToChild: '不能移动到子文件夹中',
        dragUnknownType: '未知拖拽类型',

        loginFailed: '用户名或密码错误',
        logoutConfirm: '确定要退出登录吗？',

        searchNavigationSimplified: '搜索导航功能已简化，请在目录树中点击查看',

        articleIdExpired: '文章 ID 已过期，请刷新页面后再试',

        avatarUploadSuccess: '头像上传成功',

        adminBgColorApplied: '背景颜色已应用',
        adminBgColorReset: '背景颜色已重置',
        adminTextureUploadFirst: '请先上传纹理图片',
        adminTextureSaved: '纹理配置已保存',
        adminTextureRemoved: '纹理已移除',
        adminWatermarkApplied: '水印设置已应用',
        adminArticleListUpdated: '文章列表已更新',

        draftSelectArticleFirst: '请先选择一篇文章',
        draftTitleEmpty: '标题不能为空',
        draftSaved: '草稿已保存',
        draftSaveFailed: (msg) => `草稿保存失败: ${msg}`,
        draftRestored: '已恢复草稿版本',
        draftRestoreFailed: (msg) => `恢复失败: ${msg}`,
        draftDataCorrupted: '草稿数据异常，无法删除',
        draftInvalidArticleId: '无效的文章ID，无法删除',
        draftDeleted: '草稿已删除',
        draftDeleteFailed: (msg) => `删除失败: ${msg}`,

        touchAdminRequired: '需要管理员权限',
        touchAdminRequiredDrag: '需要管理员权限才能拖拽',
        touchDragToValidTarget: '请拖拽到有效的文件夹或空白区域',
        touchMoveFailed: (msg) => `移动失败: ${msg}`,

        editorPositionModeEnter: '已进入位置管理模式，拖拽节点调整顺序',
        editorPositionModeSaved: '位置更改已保存',
        editorPositionModeCancelled: '已取消更改',

        articleServiceCannotDeleteDefaultCategory: '不能删除"未分类"文件夹',

        decoMobileNotSupported: '移动端不支持贴纸位置编辑',
        decoImageNotFound: '图片资源不存在',

        textureSolidColorApplied: '纯色背景已应用',
        textureBgReset: '背景已重置为默认',
        textureNeedAtLeastTwoColors: '至少需要两种颜色',
        textureGradientApplied: '渐变背景已应用',
        texturePaletteSaved: '色卡已保存',
        texturePaletteDeleted: '色卡已删除',
        texturePaletteNotFound: '色卡不存在',
        textureCompressingImage: '正在压缩转换图片...',
        textureImageProcessingFailed: (msg) => `图片处理失败: ${msg}`,
        textureTextureRemoved: '纹理已移除',

        imageFormatInvalid: '格式不正确，只支持 PNG、WebP、JPG 格式',
        decoUploadSuccess: (name) => `贴图 "${name}" 上传成功`,
        decoUploadFailed: (msg) => `上传失败：${msg}`,

        monitorDegraded: '⚠️ 部分服务不可用，请稍后重试',
        monitorDegradedDetail: (svc) => `⚠️ ${svc}服务不可用，部分功能受限`,
        monitorUnreachable: '🔴 无法连接到后端服务',
        monitorRestored: '✅ 服务已恢复',
    },

    monitor: {
        statusOk: '服务正常',
        statusDegraded: '服务降级',
        statusUnreachable: '无法连接',
        bannerDegraded: '⚠️ 部分服务不可用，部分功能受限',
        bannerDegradedDetail: (svc) => `⚠️ ${svc}服务不可用 — 已禁用编辑和上传功能`,
        bannerUnreachable: '🔴 无法连接到后端服务，请检查网络',
        uploadDisabled: '服务降级中，上传功能暂不可用',
        checkTimeout: '健康检查超时',
        serviceDb: '数据库',
        serviceStorage: '存储',
        noData: '无可用数据',
        tooltipTemplate: (db, st, ws, mem) => `数据库: ${db}\n存储: ${st}\nWebSocket: ${ws}\n内存: ${mem}`,
        detailDegraded: (services) => `（${services}不可用）`,
    },

    puzzle: {
        widgetTitle: '确认您是真人！',
        title: '自定义拼图图片',
        hint: '拖动滑块完成拼图——如果你想',
        completed: '✨ 拼图完成！',
        uploadBtn: '📤 上传图片',
        resetBtn: '🔄 恢复默认',
        adminHint: '上传后拖拽滑块完成拼图；恢复默认则使用主题纯色背景',
        invalidFormat: '请选择图片文件',
        imageUpdated: '拼图图片已更新',
        resetToDefault: '拼图已恢复为默认背景',
    },

    componentManager: {
        panelTitle: '🧩 组件状态',
        stateRegistered: '已注册',
        stateInitialized: '已初始化',
        stateMounted: '已挂载',
        stateUnmounted: '已卸载',
        stateError: '错误',
        stateUnknown: '未知',
        depsLabel: '依赖',
        noDeps: '无',
        desktopOnly: '仅桌面端',
        allPlatforms: '全平台',
        actionInit: '初始化',
        actionMount: '挂载',
        actionUnmount: '卸载',
        actionRemount: '重新挂载',
        initAll: '全部初始化',
        mountAll: '全部挂载',
        unmountAll: '全部卸载',
        registeredCount: (n) => `已注册 ${n} 个组件`,
        mountedCount: (n) => `已挂载 ${n} 个`,
        errorCount: (n) => `${n} 个异常`,
        debugHint: '通过 window.__REVACHOL__.ComponentManager 查看详细状态',
        enginePlaceholder: '互动引擎预留接口已就绪',
    },

    magicBox: {
        items: [
            { id: 'feather', emoji: '🪶', label: '一根白色羽毛', message: '它轻得几乎不存在。' },
            { id: 'coin',   emoji: '🪙', label: '一枚旧硬币',   message: '年份已经模糊不清。' },
            { id: 'key',    emoji: '🗝️', label: '一把生锈的钥匙', message: '它不适合任何锁。' },
            { id: 'note',   emoji: '📄', label: '一张字条',     message: '上面写着："你。"' },
            { id: 'sand',   emoji: '⏳', label: '一粒沙',       message: '它来自一个你从未去过的海滩。' },
            { id: 'thread', emoji: '🧵', label: '一颗纽扣',     message: '它被缝在什么东西上——但你不知道是什么。' },
            { id: 'mirror', emoji: '🪞', label: '一面小镜子',   message: '镜子里没有人。' },
            { id: 'void',   emoji: '🌫️', label: '（什么都没有）', message: '但箱子似乎更重了。' },
        ],
        countFormat: (n) => `已打开 ${n} 次`,
        contextMenu: {
            switchToAbsolute: '🔄 切换样式',
            switchToFixed: '🔄 切换样式',
        },
        toast: {
            uploadNotReady: '上传控件未就绪',
            imageFormatOnly: '仅支持图片格式（PNG/JPEG/WebP）',
            lidImageUpdated: '箱盖外观已更新',
            bodyImageUpdated: '箱体外观已更新',
            imageReadFailed: '图片读取失败',
            lidImageRemoved: '已恢复默认箱盖',
            bodyImageRemoved: '已恢复默认箱体',
            selectItemFirst: '请先选择要自定义的物品',
            selectItem: '请先选择物品',
            itemImageUpdated: (label) => `物品 "${label}" 贴图已更新`,
            itemImageRemoved: (label) => `物品 "${label}" 已恢复默认 Emoji`,
        },
    },

    stickerEditor: {
        addStickerBtn: '📌 添加贴纸',
        editingLabel: '✏️ 编辑中',
        toolbarTitle: '贴纸库',
        confirmBtn: '✅ 确认',
        cancelBtn: '❌ 取消',
        consoleTitle: '📚 贴纸库',
        placedLabel: '已放置',
        emptyLibrary: '贴纸库为空，请先在管理面板上传贴纸',
        mobileWarning: '贴纸编辑功能仅支持桌面端',
        ctxMoveAndResize: '📐 移动和缩放',
        ctxToggleAlign: '🔄 切换浮动方向',
        ctxRemove: '🗑️ 删除贴纸',
        savedToast: '贴纸位置已保存',
        cancelledToast: '已放弃贴纸更改',
        escHint: '再按一次 ESC 放弃更改',
        syncFailed: '贴纸保存失败，请重试',
    },

};